### ISSUE TITLE
Firefox för Android?

### ISSUE THREAD

**Issue by toso06** [peturh/swedish-newspaper-fixer#1]
Är du intresserad av att försöka få igång din extension för Firefox för Android? Den fungerar hur som helst bra för Firefox 50.0.2 för Windows (10)
![dn fixer](https://cloud.githubusercontent.com/assets/3530086/21083030/faae9914-bfe7-11e6-9171-39535a117f88.png)

[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension)

Det intressanta för mig är egentligen att få igång detta på mobilen och Firefox för Android verkar stödja extensions. Vill du själv försöka publicera en Firefox extension eller ska jag göra det?

**Comment by peturh** [comment]
Tack för att du kommer med förslag! 

Jag visste inte att Mozilla stödjer extensions på mobilen, men jag är hemma sjuk idag så jag skapar ny branch för Mozilla add on och säger till när det är upplagt!

**Comment by peturh** [comment]
Behövdes inte ens göras en branch, bara lägga upp. Den genomgår nu review. Säger till när det är klart.

**Comment by peturh** [comment]
https://addons.mozilla.org/en-US/firefox/addon/dn-fixer/

Kanske går att ladda hem även om den inte genomgått review.

**Comment by toso06** [comment]
Jag provade att installera på mobilen men det verkar inte fungera. Eventuellt för att Mozilla inte signerat ännu. 
![screenshot_20161212-112537](https://cloud.githubusercontent.com/assets/3530086/21096021/5237538a-c05e-11e6-9d97-23f4375b2ac0.png)

**Comment by peturh** [comment]
Misstänker det.

**Comment by peturh** [comment]
Nu är det testat på mobilen och det funkar fint.

Är du sugen på Dagens Industri har jag den också (numera på mobilen också!): 
https://github.com/peturh/di.se-Fixer

**Comment by toso06** [comment]
Tack!
