### ISSUE TITLE
Possibility to have the urls configurable

### ISSUE THREAD

**Issue by Mharlin** [peturh/swedish-newspaper-fixer#3]
Great plugin!

If I could wish for one additional thing it would be a config page to configure the urls which the extension is activated for.

Keep up the good work and with the help of your other branch I realize that it can be added manually as well.

**Comment by peturh** [comment]
Tror inte jag fattar riktigt. I manifest.json står det vilka sidor pluginet funkar på. I DN fallet har dom bara en domän som jag känner till: dn.se i http och https. Vilka andra sidor har dom?

**Comment by Mharlin** [comment]
Jag tänkte mer så att man kunde lägga till flera sidor som t.ex. svd.se och di.se men utan att behöva gå in i manifest.json utan välja options för pluginet och ställa in det den vägen istället.

**Comment by peturh** [comment]
Tyvärr går det inte, för att ändra innehållet (t.ex. ta bort dom-element) på sidan måste pluginet få access till sidan, detta sker via manifest.json. Däremot har jag tänkt på att slå ihop dn-fixer och di-fixer... 

SvD går förövrigt inte att fixa med ett sånt här plugin. Men jag har ju gjort en du fixer, kolla in den om du inte redan gjort det.

**Comment by Mharlin** [comment]
Toppen, tack!
